[NFU] add build script
The configure script is called with '--extra-cflags="-U __OPTIMIZE__"'
as this is needed to avoid the following error when using gcc 13.2.0 on
Ubuntu 23.10:

In file included from ../hw/riscv/cbqri_bandwidth.c:22:
../hw/riscv/cbqri_bandwidth.c: In function ‘riscv_cbqri_bc_class_init’:
/home/pdp7/dev/qemu/include/qemu/osdep.h:261:35: error: call to ‘qemu_build_not_reached_always’ declared with attribute error: code path is reachable
  261 | #define qemu_build_not_reached()  qemu_build_not_reached_always()
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pdp7/dev/qemu/include/hw/qdev-core.h:960:13: note: in expansion of macro ‘qemu_build_not_reached’
  960 |             qemu_build_not_reached();                                   \
      |             ^~~~~~~~~~~~~~~~~~~~~~
../hw/riscv/cbqri_bandwidth.c:571:5: note: in expansion of macro ‘device_class_set_props’
  571 |     device_class_set_props(dc, riscv_cbqri_bc_properties);
      |     ^~~~~~~~~~~~~~~~~~~~~~

Link: https://gitlab.com/qemu-project/qemu/-/issues/363